CREATE TABLE tblUser(
userId VARCHAR(30) PRIMARY KEY,
password VARCHAR(30) NOT NULL,
paymentAmount INT DEFAULT 0,
birthDate DATE NOT NULL,
phone VARCHAR(11) NOT NULL,
grade VARCHAR(10) NOT NULL,
temp FLOAT DEFAULT 36.5,
manager TINYINT(1) DEFAULT 0
);